encoding: utf-8

# SEO相关信息
title: Kouen 
description: Kouen
keywords: Kouen,Blog,Java,Html,JavaScript,CD,Share
author: Kouen
footerText: 'Copyright © 2021 Kouen

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://kouen.live'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/86335

# 菜单
menu:
  - title: 首页
    url: /
  - title: 分類
    url: /pages/categories.html
  - title: 検索
    url: /pages/search.html
  - title: リンク
    url: /pages/links.html
  - title: コメント
    url: /pages/chat.html
  - title: Infor
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: Google
    url: https://www.google.co.jp
  - title: Getchu
    url: https://www.getchu.com


